"use client";
import React, { useState } from 'react';
import { ethers } from 'ethers';

export default function MintCow() {
    const [isLoading, setIsLoading] = useState(false);
        const [statusMessage, setStatusMessage] = useState('');

            // Fungsi buat mint NFT (Nanti kita sesuaikan dengan alamat kontrak Abang)
                const handleMint = async () => {
                        try {
                                    setIsLoading(true);
                                                setStatusMessage('Menyiapkan transaksi...');

                                                            if (!window.ethereum) {
                                                                            alert('Tolong install MetaMask dulu!');
                                                                                            setIsLoading(false);
                                                                                                            return;
                                                                                                                        }

                                                                                                                                    const provider = new ethers.BrowserProvider(window.ethereum);
                                                                                                                                                const signer = await provider.getSigner();

                                                                                                                                                            // SEMENTARA: Ini simulasi atau nanti kita masukkan address kontrak FarmVLivestock Abang
                                                                                                                                                                        setStatusMessage('Silakan konfirmasi transaksi di wallet...');
                                                                                                                                                                                    
                                                                                                                                                                                                // Contoh simulasi waktu tunggu transaksi (nanti kita ganti panggil fungsi smart contract aslinya)
                                                                                                                                                                                                            setTimeout(() => {
                                                                                                                                                                                                                            setIsLoading(false);
                                                                                                                                                                                                                                            setStatusMessage('Berhasil mencetak Sapi NFT! 🐄🎉');
                                                                                                                                                                                                                                                        }, 3000);

                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                            console.error(error);
                                                                                                                                                                                                                                                                                        setIsLoading(false);
                                                                                                                                                                                                                                                                                                    setStatusMessage('Transaksi gagal / dibatalkan.');
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                            <div className="bg-white p-8 rounded-2xl shadow-md border border-gray-100 max-w-md w-full text-center">
                                                                                                                                                                                                                                                                                                                                        {/* Gambar Ilustrasi Sapi / Ikon */}
                                                                                                                                                                                                                                                                                                                                                    <div className="text-6xl mb-4">🐮</div>
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                            <h3 className="text-2xl font-bold text-gray-800 mb-2">Mint Sapi FarmV</h3>
                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-gray-500 text-sm mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                        Miliki NFT sapi unik di jaringan IOPn Testnet dan mulai kelola peternakanmu.
                                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Tombol Mint */}
                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={handleMint}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            disabled={isLoading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className={`w-full py-3 px-4 rounded-xl font-bold text-white transition-all shadow-md ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                isLoading 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ? 'bg-gray-400 cursor-not-allowed' 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : 'bg-green-600 hover:bg-green-700 active:scale-95'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {isLoading ? 'Sedang Diproses...' : '🚀 Mint Sapi Sekarang'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Status Pesan */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {statusMessage && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="mt-4 text-sm font-medium text-green-600 bg-green-50 p-3 rounded-lg border border-green-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {statusMessage}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
