"use client";
import { useState } from 'react';
import { ethers } from 'ethers';
// IMPORT ABI KONTRAK SAPI ABANG DI SINI
import FarmVLivestockABI from '../constants/FarmVLivestock.json';

export default function Profile() {
    const [account, setAccount] = useState('');
        const [balance, setBalance] = useState('');
            const [cowCount, setCowCount] = useState(0); // Buat simpen jumlah sapi
                const [badge, setBadge] = useState('🌱 Warga Baru'); // Badge default
                    const [isConnecting, setIsConnecting] = useState(false);

                        // Ambil address contract sapi dari .env
                            const contractAddress = process.env.NEXT_PUBLIC_LIVESTOCK_CONTRACT_ADDRESS;

                                const formatAddress = (address) => {
                                        return `${address.substring(0, 6)}...${address.substring(address.length - 4)}`;
                                            };

                                                // Logika buat nentuin level/badge user
                                                    const determineBadge = (count) => {
                                                            if (count >= 10) return '👑 Juragan Sapi';
                                                                    if (count >= 5) return '🤠 Peternak Pro';
                                                                            if (count >= 1) return '🚜 Peternak Aktif';
                                                                                    return '🌱 Warga Baru';
                                                                                        };

                                                                                            const connectWallet = async () => {
                                                                                                    if (!window.ethereum) return alert("MetaMask belum ter-install, Bang!");

                                                                                                            try {
                                                                                                                        setIsConnecting(true);
                                                                                                                                    const provider = new ethers.BrowserProvider(window.ethereum);
                                                                                                                                                const signer = await provider.getSigner();
                                                                                                                                                            const address = await signer.getAddress();
                                                                                                                                                                        
                                                                                                                                                                                    // 1. Ambil saldo IOPn
                                                                                                                                                                                                const balanceBigInt = await provider.getBalance(address);
                                                                                                                                                                                                            setAccount(address);
                                                                                                                                                                                                                        setBalance(parseFloat(ethers.formatEther(balanceBigInt)).toFixed(4));

                                                                                                                                                                                                                                    // 2. KONEK KE SMART CONTRACT BUAT CEK JUMLAH SAPI (Sesuai Kontrak Abang)
                                                                                                                                                                                                                                                const contract = new ethers.Contract(contractAddress, FarmVLivestockABI, provider);
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                        // Panggil balanceOf dari ERC721 untuk ngecek jumlah NFT sapi punya user ini
                                                                                                                                                                                                                                                                                    const countBigInt = await contract.balanceOf(address);
                                                                                                                                                                                                                                                                                                const count = Number(countBigInt);
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                        setCowCount(count);
                                                                                                                                                                                                                                                                                                                                    setBadge(determineBadge(count)); // Set badge sesuai jumlah sapi

                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                        console.error("Gagal connect MetaMask:", error);
                                                                                                                                                                                                                                                                                                                                                                } finally {
                                                                                                                                                                                                                                                                                                                                                                            setIsConnecting(false);
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                    <div className="max-w-md mx-auto mt-10 p-6 bg-white rounded-2xl shadow-lg border border-gray-100">
                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex items-center justify-between mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-2xl font-bold text-gray-800">🧑‍🌾 Profil Peternak</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                {account && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="px-3 py-1 bg-green-100 text-green-700 text-xs font-bold rounded-full border border-green-200">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {badge} {/* NAMPILIN BADGE DI SINI */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {!account ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={connectWallet} disabled={isConnecting} className="w-full bg-blue-500 hover:bg-blue-600 text-white font-bold py-3 px-4 rounded-xl shadow-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {isConnecting ? 'Menghubungkan...' : '🦊 Connect Wallet'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="p-4 bg-gray-50 rounded-xl border border-gray-200 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-sm text-gray-500 font-medium">Dompet ID</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="font-mono text-gray-800 font-bold">{formatAddress(account)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex-1 p-4 bg-blue-50 rounded-xl border border-blue-100 flex flex-col items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-xs text-blue-500 font-bold mb-1">Saldo Koin</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="font-mono text-blue-900 font-bold text-lg">{balance} <span className="text-sm">IOPn</span></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex-1 p-4 bg-orange-50 rounded-xl border border-orange-100 flex flex-col items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-xs text-orange-500 font-bold mb-1">Total Sapi</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="font-mono text-orange-900 font-bold text-lg">{cowCount} <span className="text-sm">Ekor</span></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
